services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 800m
    ports:
      - "9411:9411"
    networks:
      - izrael-network

  configserver:
    image: izrael13/configserver:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - izrael-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  eurekaserver:
    image: izrael13/eurekaserver:latest
    mem_limit: 800m
    ports:
      - "8065:8065"
    networks:
      - izrael-network
    depends_on:
      - configserver
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  hotels:
    image: izrael13/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - izrael-network
    depends_on:
      - configserver
      - eurekaserver
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  rooms:
    image: izrael13/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - izrael-network
    depends_on:
      - configserver
      - eurekaserver
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  reservations:
    image: izrael13/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - izrael-network
    depends_on:
      - configserver
      - eurekaserver
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    
  gatewayserver:
    image: izrael13/gatewayserver:latest
    mem_limit: 800m
    ports:
      - "8066:8066"
    networks:
      - izrael-network
    depends_on:
      - configserver
      - eurekaserver
      - hotels
      - rooms
      - reservations
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

networks:
  izrael-network: